# Generated by Django 5.1.3 on 2024-11-23 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='household',
            name='enddate_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
