# Generated by Django 5.1.3 on 2024-11-23 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0002_household_enddate_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='household',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='household',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='nationality',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
