# Generated by Django 5.1.3 on 2024-11-14 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='status',
            field=models.CharField(choices=[('vacant', 'Vacant'), ('owned', 'Owned'), ('developer', 'Developer Owned')], default='vacant', max_length=20),
        ),
    ]
