# Generated by Django 5.1.3 on 2024-11-14 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0002_house_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='handover',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='status',
            field=models.CharField(choices=[('vacant', 'Vacant'), ('owned', 'Owned'), ('developer', 'Developer')], default='developer', max_length=20),
        ),
    ]
