# Generated by Django 5.1.3 on 2024-11-14 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0004_alter_house_unit_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='owner',
            name='kra_pin',
            field=models.CharField(max_length=20, unique=True, verbose_name='KRA PIN'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='phone_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
