# Generated by Django 5.1.3 on 2024-11-15 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0005_alter_owner_email_alter_owner_kra_pin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='house',
        ),
        migrations.AddField(
            model_name='owner',
            name='houses',
            field=models.ManyToManyField(blank=True, related_name='owner_set', to='house.house'),
        ),
    ]
