# Generated by Django 5.1.3 on 2024-11-15 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0006_remove_owner_house_owner_houses'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='houses',
            new_name='house',
        ),
    ]
