# Generated by Django 5.1.3 on 2024-12-04 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0007_rename_houses_owner_house'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='garbage_collected',
            field=models.BooleanField(default=False, verbose_name='Garbage Collected'),
        ),
        migrations.AddField(
            model_name='house',
            name='garbage_collection_date',
            field=models.DateField(null=True, verbose_name='Last Garbage Collection Date'),
        ),
    ]
