# Generated by Django 5.1.3 on 2024-11-26 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meter', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meterreading',
            options={'ordering': ['-reading_date', '-id']},
        ),
        migrations.AddField(
            model_name='meterreading',
            name='rate_per_unit',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=6),
        ),
    ]
