# Generated by Django 5.1.3 on 2024-11-26 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meter', '0002_alter_meterreading_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meterreading',
            name='rate_per_unit',
            field=models.DecimalField(decimal_places=2, default=171, max_digits=6),
        ),
    ]
